# MAINTAINER camilo@camilo.fm

FROM consul:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install apt-transport-https ca-certificates wget -y --no-install-recommends && \
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add - && \
    echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list && \
    apt-get update && \
    apt-get install jitsi-videobridge -y --no-install-recommends && \
    apt-get remove wget -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

COPY ./config/jitsi-videobridge/templates/ /etc/jitsi/videobridge/templates/
COPY ./scripts/jvb.sh /etc/jitsi/videobridge/init.sh

RUN chown -R jvb:jitsi /etc/jitsi/videobridge/

EXPOSE 4443 10000

WORKDIR /etc/jitsi/videobridge

CMD ./init.sh
