FROM consul:latest
MAINTAINER camilo@camilo.fm

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install apt-transport-https ca-certificates wget -y --no-install-recommends && \
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add - && \
    echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list && \
    apt-get update && \
    apt-get install jicofo -y --no-install-recommends && \
    apt-get remove wget -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

COPY ./config/jicofo/templates /etc/jitsi/jicofo/templates/
COPY ./scripts/jicofo.sh /etc/jitsi/jicofo/init.sh

RUN chown -R jicofo:jitsi /etc/jitsi/jicofo/

EXPOSE 6666 6667

WORKDIR /etc/jitsi/jicofo

CMD ./init.sh
