FROM consul:latest
MAINTAINER camilo@camilo.fm

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install prosody -y --no-install-recommends

COPY ./config/prosody/certs/ /etc/prosody/certs/
COPY ./config/prosody/templates/ /etc/prosody/templates/
COPY ./scripts/prosody.sh /etc/prosody/init.sh

RUN chown -R prosody:prosody /etc/prosody/

EXPOSE 5222 5269 5280 5281 5347 5555 5556

WORKDIR /etc/prosody

CMD ./init.sh
