# MAINTAINER camilo@camilo.fm

FROM consul:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        nginx \
        wget  && \
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add - && \
    echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list && \
    apt-get update && \
    apt-get install jitsi-meet-web -y --no-install-recommends && \
    groupadd jitsi && \
    useradd -d /usr/share/jitsi-meet -s /sbin/nologin -g jitsi meet && \
    mkdir -p /etc/jitsi/meet && \
    chown -R meet:jitsi /etc/jitsi/meet/ /usr/share/jitsi-meet && \
    apt-get remove wget -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

COPY ./config/prosody/certs/ /etc/jitsi/meet/certs/
COPY ./config/jitsi-meet/templates/ /etc/jitsi/meet/templates/
COPY ./scripts/meet.sh /etc/jitsi/meet/init.sh

RUN chown -R meet:jitsi /etc/jitsi/meet

WORKDIR /etc/jitsi/meet

EXPOSE 80 443

CMD ./init.sh
