FROM ubuntu:updated
MAINTAINER camilo@camilo.fm

SHELL ["/bin/bash", "-c"]

ARG SHOULD_BUILD

RUN [[ $SHOULD_BUILD != true ]] && \
    apt-get install prosody -y --no-install-recommends || true

ARG RELEASE
ARG REPOSITORY

RUN [[ $SHOULD_BUILD == true ]] && \
    apt-get install git make lua5.1 luarocks \
        liblua5.1-dev libidn11-dev libssl-dev libexpat-dev -y --no-install-recommends && \
    luarocks install luasocket && \
    luarocks install luaexpat && \
    luarocks install luafilesystem && \
    luarocks install luasec && \
    luarocks install luabitop && \

    mkdir -p /etc/prosody/ /var/lib/prosody /var/log/prosody /var/run/prosody && \
    useradd -d /etc/prosody -s /sbin/nologin prosody && \
    chown -R prosody:prosody /etc/prosody/ /var/lib/prosody /var/log/prosody /var/run/prosody && \

    # Downloading and installing Prosody
    git clone --depth=1 --branch $RELEASE $REPOSITORY /root/prosody && \
    cd /root/prosody/ && \
    ./configure --ostype=debian --prefix= --require-config && \
    make && \
    make install && \
    rm /root/prosody/ -rf && \

    apt-get remove git make -y && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y || true

USER prosody
WORKDIR /etc/prosody

CMD prosody
