# MAINTAINER camilo@camilo.fm

FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ant \
        git \
        default-jdk-headless \
        maven

ARG RELEASE
ARG RELEASE_VERSION
ARG REPOSITORY

RUN git clone --depth=1 --branch $RELEASE $REPOSITORY /root/jitsi-videobridge && \
    cd /root/jitsi-videobridge && \
    mvn package \
        -f pom.xml \
        -DskipTests && \
    mvn dependency:get \
        -DgroupId=org.apache.maven \
        -DartifactId=maven-ant-tasks \
        -Dversion=2.1.3 && \
    ant -lib /root/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 -Dlabel=$RELEASE_VERSION dist.lin64 && \
    mv /root/jitsi-videobridge/dist/linux/jitsi-videobridge-linux-x64-$RELEASE_VERSION.zip /root/jitsi-videobridge.zip

FROM consul:latest

SHELL ["/bin/bash", "-c"]

COPY --from=0 /root/jitsi-videobridge.zip /root/jitsi-videobridge.zip
COPY --from=0 /root/jitsi-videobridge/resources/install/debian/init.d /etc/init.d/jitsi-videobridge

RUN apt-get update && \
    apt-get install default-jre-headless unzip -y --no-install-recommends && \
    unzip /root/jitsi-videobridge.zip -d /root/jitsi-videobridge && \
    mv /root/jitsi-videobridge/jitsi-videobridge-linux-x64-* /usr/share/jitsi-videobridge && \
    chmod 755 /etc/init.d/jitsi-videobridge && \
    mkdir -p /etc/jitsi/videobridge /var/log/jitsi &&\
    groupadd jitsi && \
    useradd -d /usr/share/jitsi-videobridge -s /sbin/nologin -g jitsi jvb && \
    chown -R jvb:jitsi /etc/jitsi/videobridge/ /var/log/jitsi /usr/share/jitsi-videobridge && \
    apt-get remove unzip -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

COPY ./config/jitsi-videobridge/templates/ /etc/jitsi/videobridge/templates/
COPY ./scripts/jvb.sh /etc/jitsi/videobridge/init.sh

RUN chown -R jvb:jitsi /etc/jitsi/videobridge/

EXPOSE 4443 4443/udp 10000 10000/udp

WORKDIR /etc/jitsi/videobridge

CMD ./init.sh
