# MAINTAINER camilo@camilo.fm

FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bzip2 \
        ca-certificates \
        git \
        make \
        tar \
        wget

ARG RELEASE
ARG RELEASE_VERSION
ARG REPOSITORY

RUN git clone --depth=1 --branch $RELEASE $REPOSITORY /root/jitsi-meet && \
    cd /root/jitsi-meet && \
    wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash&& \
    source /root/.nvm/nvm.sh && nvm install 6 && \
    npm install && \
    make && \
    make source-package && \
    tar -xjf /root/jitsi-meet/jitsi-meet.tar.bz2 -C /tmp/

FROM consul:latest

SHELL ["/bin/bash", "-c"]

COPY --from=0 /tmp/jitsi-meet/ /usr/share/jitsi-meet/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        nginx && \
    mkdir -p /etc/jitsi/meet && \
    groupadd jitsi && \
    useradd -d /usr/share/jitsi-meet -s /sbin/nologin -g jitsi meet && \
    chown -R meet:jitsi /etc/jitsi/meet/ /usr/share/jitsi-meet && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

COPY ./config/prosody/certs/ /etc/jitsi/meet/certs/
COPY ./config/jitsi-meet/templates/ /etc/jitsi/meet/templates/
COPY ./scripts/meet.sh /etc/jitsi/meet/init.sh

RUN chown -R meet:jitsi /etc/jitsi/meet

WORKDIR /etc/jitsi/meet

EXPOSE 80 443

CMD ./init.sh
