FROM ubuntu:latest
MAINTAINER camilo@camilo.fm

SHELL ["/bin/bash", "-c"]

RUN apt-get-update && \
    apt-get install -y --no-install-recommends \
        ant \
        git \
        default-jdk-headless \
        maven

ARG RELEASE
ARG RELEASE_VERSION
ARG REPOSITORY

RUN git clone --depth=1 --branch $RELEASE $REPOSITORY /root/jicofo && \
    cd /root/jicofo && \
    mvn package \
        -f pom.xml \
        -DskipTests && \
    mvn dependency:get \
        -DgroupId=org.apache.maven \
        -DartifactId=maven-ant-tasks \
        -Dversion=2.1.3 && \
    ant -lib /root/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 -Dlabel=$RELEASE_VERSION dist.lin64 && \
    mv /root/jicofo/dist/linux/jicofo-linux-x64-$RELEASE_VERSION.zip /root/jicofo.zip

FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

COPY --from=0 /root/jicofo.zip /root/jicofo.zip
COPY --from=0 /root/jicofo/resources/install/debian/init.d /etc/init.d/jicofo

RUN apt-get update && \
    apt-get install default-jre-headless unzip -y --no-install-recommends && \
    unzip /root/jicofo.zip -d /root/jicofo && \
    mv /root/jicofo/jicofo-linux-x64-* /usr/share/jicofo && \
    chmod 755 /etc/init.d/jicofo && \
    mkdir -p /etc/jitsi/jicofo /var/log/jitsi &&\
    groupadd jitsi && \
    useradd -d /usr/share/jicofo -s /sbin/nologin -g jitsi jicofo && \
    chown -R jicofo:jitsi /etc/jitsi/jicofo/ /var/log/jitsi /usr/share/jicofo && \
    apt-get remove unzip -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

USER jicofo
WORKDIR /etc/jitsi/jicofo

CMD tail -f /dev/null
