# MAINTAINER camilo@camilo.fm

FROM consul:latest

SHELL ["/bin/bash", "-c"]

ARG RELEASE
ARG REPOSITORY

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        gcc \
        git \
        libexpat-dev \
        libidn11-dev \
        liblua5.1-dev \
        libssl-dev \
        lua5.1 \
        luarocks \
        make \
        unzip && \
    luarocks install luasec && \
    luarocks install luaexpat && \
    luarocks install luafilesystem && \
    luarocks install luabitop && \

    mkdir -p /etc/prosody/ /etc/prosody/conf.d/ /var/lib/prosody/ /var/log/prosody/ && \
    useradd -d /etc/prosody -s /sbin/nologin prosody && \
    chown -R prosody:prosody /etc/prosody/ /var/lib/prosody/ /var/log/prosody/ && \

    # Downloading and installing Prosody
    git clone --depth=1 --branch $RELEASE $REPOSITORY /root/prosody && \
    cd /root/prosody/ && \
    ./configure --ostype=debian --prefix=/ --require-config && \
    make && \
    make install && \
    rm /root/prosody/ -rf && \

    apt-get remove gcc git make unzip -y && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y

COPY ./config/prosody/certs/ /etc/prosody/certs/
COPY ./config/prosody/templates/ /etc/prosody/templates/
COPY ./config/prosody/plugins_or_modules/ /usr/lib/prosody/modules/
COPY ./scripts/prosody.sh /etc/prosody/init.sh

RUN chown -R prosody:prosody /etc/prosody/ /usr/lib/prosody/

EXPOSE 5222 5269 5280 5281 5347 5554 5555

WORKDIR /etc/prosody

CMD ./init.sh
