version: '3'
services:
  jitsi-videobridge:
    image: debugmaster/jitsi-videobridge
    environment:
     - ADVERTISED_ADDRESS
     - XMPP_SERVER
    ports:
     - "4443:4443"
     - "4443:4443/udp"
     - "10000:10000"
     - "10000:10000/udp"
