version: '3'
services:
  prosody:
    image: debugmaster/prosody
    environment:
     - ADVERTISED_ADDRESS
     - DOMAIN
     - XMPP_SERVER
     - PROSODY_C2S_SERVICE_PORT
     - PROSODY_S2S_SERVICE_PORT
     - PROSODY_HTTP_SERVICE_PORT
     - PROSODY_HTTPS_SERVICE_PORT
     - PROSODY_COMPONENT_SERVICE_PORT
    ports:
     - "$PROSODY_C2S_SERVICE_PORT:5222"
     - "$PROSODY_S2S_SERVICE_PORT:5269"
     - "$PROSODY_HTTP_SERVICE_PORT:5280"
     - "$PROSODY_HTTPS_SERVICE_PORT:5281"
     - "$PROSODY_COMPONENT_SERVICE_PORT:5347"
     - "5554-5555:5554-5555"
