FROM ubuntu:updated
MAINTAINER camilo@camilo.fm

SHELL ["/bin/bash", "-c"]

ARG SHOULD_BUILD

RUN [[ $SHOULD_BUILD != true ]] && \
    apt-get install wget -y && \
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add - && \
    apt-get install jicofo -y || true

RUN apt-get install -y --no-install-recommends \
        ant \
        git \
        default-jdk-headless \
        maven

ARG RELEASE
ARG REPOSITORY

RUN git clone --depth=1 --branch $RELEASE $REPOSITORY /root/jicofo

WORKDIR /root/jicofo
RUN mvn package \
        -f pom.xml \
        -DskipTests
RUN mvn dependency:get \
        -DgroupId=org.apache.maven \
        -DartifactId=maven-ant-tasks \
        -Dversion=2.1.3

ARG RELEASE_VERSION

RUN ant -lib /root/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 -Dlabel=$RELEASE_VERSION dist.lin64 && \
    mv /root/jicofo/dist/linux/jicofo-linux-x64-$RELEASE_VERSION.zip /root/jicofo.zip

FROM ubuntu:updated

SHELL ["/bin/bash", "-c"]

COPY --from=0 /root/jicofo.zip /root/jicofo.zip
COPY --from=0 /root/jicofo/resources/install/debian/init.d /etc/init.d/jicofo

RUN apt-get install default-jre-headless unzip -y --no-install-recommends && \
    unzip /root/jicofo.zip -d /root/jicofo && \
    mv /root/jicofo/jicofo-linux-x64-* /usr/share/jicofo && \
    chmod 755 /etc/init.d/jicofo && \
    mkdir -p /etc/jitsi/jicofo /var/log/jitsi &&\
    groupadd jitsi && \
    useradd -d /usr/share/jicofo -s /sbin/nologin -g jitsi jicofo && \
    chown -R jicofo:jitsi /etc/jitsi/jicofo/ /var/log/jitsi /usr/share/jicofo && \
    apt-get remove unzip -y && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    apt-get autoclean -y

USER jicofo
WORKDIR /etc/jitsi/jicofo
CMD tail -f /dev/null
